const encoder = new TextEncoder();
const COOKIE = "arthur_cms_session";
const MAX_AGE = 60 * 60 * 12;
const security = { "cache-control": "no-store, max-age=0", "content-security-policy": "default-src 'none'; frame-ancestors 'none'", "referrer-policy": "no-referrer", "x-content-type-options": "nosniff", "x-frame-options": "DENY" };

export class PublicError extends Error { constructor(message, status = 400, code = "invalid_request") { super(message); this.status = status; this.code = code; } }
export function json(data, init = {}) { const headers = new Headers({ ...security, ...(init.headers || {}) }); headers.set("content-type", "application/json; charset=utf-8"); return new Response(JSON.stringify(data), { ...init, headers }); }
export function handleError(error) { if (error instanceof PublicError) return json({ ok: false, error: error.message, code: error.code }, { status: error.status }); const requestId = crypto.randomUUID(); console.error("CMS error", { requestId, name: error?.name }); return json({ ok: false, error: "Er ging iets mis. Probeer het opnieuw.", code: "server_error", requestId }, { status: 500 }); }
export function required(env, key) { if (!env?.[key]) throw new PublicError("De beheeromgeving is nog niet volledig ingesteld.", 503, "configuration_error"); return env[key]; }
export async function readJson(request, max = 300000) { if (!(request.headers.get("content-type") || "").toLowerCase().startsWith("application/json")) throw new PublicError("Ongeldig verzoekformaat.", 415); const text = await request.text(); if (encoder.encode(text).byteLength > max) throw new PublicError("Dit verzoek is te groot.", 413); try { return JSON.parse(text || "{}"); } catch { throw new PublicError("Ongeldige JSON."); } }
function b64(bytes) { let s = ""; for (const byte of bytes) s += String.fromCharCode(byte); return btoa(s).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/g, ""); }
function unb64(value) { const b = atob(String(value).replace(/-/g, "+").replace(/_/g, "/") + "===".slice((String(value).length + 3) % 4)); return Uint8Array.from(b, c => c.charCodeAt(0)); }
async function key(secret) { return crypto.subtle.importKey("raw", encoder.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign", "verify"]); }
async function signature(value, secret) { return b64(new Uint8Array(await crypto.subtle.sign("HMAC", await key(secret), encoder.encode(value)))); }
async function equal(a, b) { const da = new Uint8Array(await crypto.subtle.digest("SHA-256", encoder.encode(String(a)))); const db = new Uint8Array(await crypto.subtle.digest("SHA-256", encoder.encode(String(b)))); let diff = 0; for (let i = 0; i < da.length; i++) diff |= da[i] ^ db[i]; return diff === 0; }
function cookies(header = "") { return Object.fromEntries(header.split(";").map(p => p.trim().split(/=(.*)/s)).filter(p => p[0])); }
function sameOrigin(request) { const url = new URL(request.url); const origin = request.headers.get("origin"); if (origin && origin !== url.origin) throw new PublicError("Verzoek van een andere website geweigerd.", 403, "origin_rejected"); if (!origin && request.headers.get("sec-fetch-site") && request.headers.get("sec-fetch-site") !== "same-origin") throw new PublicError("Verzoek van een andere website geweigerd.", 403, "origin_rejected"); }
export async function createSession(secret, url) { const csrf = b64(crypto.getRandomValues(new Uint8Array(24))); const payload = b64(encoder.encode(JSON.stringify({ exp: Math.floor(Date.now() / 1000) + MAX_AGE, csrf }))); const secure = new URL(url).protocol === "https:" ? "; Secure" : ""; return `${COOKIE}=${payload}.${await signature(payload, secret)}; Path=/; HttpOnly; SameSite=Strict${secure}; Max-Age=${MAX_AGE}`; }
export async function session(request, env) { const token = cookies(request.headers.get("cookie"))[COOKIE]; if (!token) return null; const [payload, sig, extra] = token.split("."); if (!payload || !sig || extra || !(await equal(await signature(payload, required(env, "CMS_SESSION_SECRET")), sig))) return null; try { const data = JSON.parse(new TextDecoder().decode(unb64(payload))); return data.exp > Date.now() / 1000 && data.csrf ? data : null; } catch { return null; } }
export async function requireSession(context, mutation = false) { const current = await session(context.request, context.env); if (!current) throw new PublicError("Log opnieuw in.", 401, "session_expired"); if (mutation) { sameOrigin(context.request); if (!(await equal(context.request.headers.get("x-cms-csrf") || "", current.csrf))) throw new PublicError("Beveiligingscontrole mislukt. Vernieuw de pagina.", 403, "csrf_rejected"); } return current; }
export async function login(context) { sameOrigin(context.request); const value = String((await readJson(context.request, 4096)).password || ""); if (!value || !(await equal(value, required(context.env, "CMS_PASSWORD")))) throw new PublicError("Het wachtwoord klopt niet.", 401, "invalid_credentials"); return json({ ok: true }, { headers: { "set-cookie": await createSession(required(context.env, "CMS_SESSION_SECRET"), context.request.url) } }); }
export function logout(context) { return json({ ok: true }, { headers: { "set-cookie": `${COOKIE}=; Path=/; HttpOnly; SameSite=Strict; Max-Age=0` } }); }
