import { PublicError, required } from "./_core.js";
const encoder = new TextEncoder();
const decode = new TextDecoder();
export function repoConfig(env) { return { owner: required(env, "GITHUB_OWNER"), repo: required(env, "GITHUB_REPO"), branch: env.GITHUB_BRANCH || "master", token: required(env, "GITHUB_TOKEN") }; }
const path = value => String(value).split("/").map(encodeURIComponent).join("/");
async function request(config, url, init = {}) { const headers = new Headers(init.headers); headers.set("accept", "application/vnd.github+json"); headers.set("authorization", `Bearer ${config.token}`); headers.set("user-agent", "arthur-cms"); headers.set("x-github-api-version", "2022-11-28"); const response = await fetch(`https://api.github.com${url}`, { ...init, headers }); if (!response.ok) { if (response.status === 404) throw new PublicError("Inhoud niet gevonden.", 404, "not_found"); throw new PublicError("GitHub kon de inhoud niet laden of opslaan.", response.status === 401 || response.status === 403 ? 503 : 409, "github_error"); } return response; }
async function api(config, url, init) { return (await request(config, url, init)).json(); }
const base = c => `/repos/${encodeURIComponent(c.owner)}/${encodeURIComponent(c.repo)}`;
export async function listMarkdown(config) { const tree = await api(config, `${base(config)}/git/trees/${encodeURIComponent(config.branch)}?recursive=1`); return (tree.tree || []).filter(x => x.type === "blob" && /^content\/(?!.*(?:^|\/)\.)[\wÀ-ž .-]+(?:\/[\wÀ-ž .-]+)*\.md$/u.test(x.path)).map(x => x.path).sort(); }
export async function file(config, filename) { const data = await api(config, `${base(config)}/contents/${path(filename)}?ref=${encodeURIComponent(config.branch)}`); return { path: data.path, sha: data.sha, content: data.content ? decode.decode(Uint8Array.from(atob(data.content.replace(/\n/g, "")), c => c.charCodeAt(0))) : "" }; }
export function base64(value) { let binary = ""; for (const byte of encoder.encode(value)) binary += String.fromCharCode(byte); return btoa(binary); }
export async function commit(config, writes, deletes, message) { const ref = await api(config, `${base(config)}/git/ref/heads/${encodeURIComponent(config.branch)}`); const head = await api(config, `${base(config)}/git/commits/${ref.object.sha}`); const tree = []; const revisions = {}; for (const write of writes) { const blob = await api(config, `${base(config)}/git/blobs`, { method: "POST", body: JSON.stringify({ content: base64(write.content), encoding: "base64" }) }); tree.push({ path: write.path, mode: "100644", type: "blob", sha: blob.sha }); revisions[write.path] = blob.sha; } for (const filename of deletes) tree.push({ path: filename, mode: "100644", type: "blob", sha: null }); const createdTree = await api(config, `${base(config)}/git/trees`, { method: "POST", body: JSON.stringify({ base_tree: head.tree.sha, tree }) }); const created = await api(config, `${base(config)}/git/commits`, { method: "POST", body: JSON.stringify({ message, tree: createdTree.sha, parents: [ref.object.sha] }) }); await api(config, `${base(config)}/git/refs/heads/${encodeURIComponent(config.branch)}`, { method: "PATCH", body: JSON.stringify({ sha: created.sha, force: false }) }); return revisions; }
