import { PublicError, handleError, json, requireSession } from "./_core.js";
import { file, listMarkdown, repoConfig } from "./_github.js";
export function validPath(value) { const path = String(value || ""); if (!/^content\/(?!.*(?:^|\/)\.)(?:[\wÀ-ž .-]+\/)*[\wÀ-ž .-]+\.md$/u.test(path) || path.includes("..") || path.length > 240) throw new PublicError("Ongeldig inhoudspad.", 400, "invalid_path"); return path; }
export function validManagedPath(value) { return value === "hugo.yaml" ? value : validPath(value); }
export function splitMarkdown(source) { const text = String(source).replace(/\r\n/g, "\n"); const yaml = text.startsWith("---\n"), toml = text.startsWith("+++\n"); if (!yaml && !toml) return { frontMatter: "", format: "yaml", body: text }; const marker = yaml ? "---" : "+++"; const end = text.indexOf(`\n${marker}\n`, 4); if (end < 0) throw new PublicError("Deze pagina heeft ongeldige front matter.", 422, "malformed_content"); return { frontMatter: text.slice(4, end), format: yaml ? "yaml" : "toml", body: text.slice(end + 5) }; }
export function titleOf(frontMatter, fallback) { return frontMatter.match(/^title\s*[:=]\s*["']?(.+?)["']?\s*$/mi)?.[1] || fallback; }
export function dateOf(frontMatter) { return frontMatter.match(/^(?:date|publishDate)\s*[:=]\s*["']?([^"'\n]+)/mi)?.[1]?.trim() || ""; }
export function groupOf(path) { if (path === "content/homepage.md") return "Startpagina"; if (path === "content/nieuwsbrief.md") return "Nieuwsbrief"; if (path.startsWith("content/snippets/")) return "Artikelen"; return "Pagina's"; }
export async function onRequestGet(context) { try { await requireSession(context); const query = new URL(context.request.url).searchParams; const config = repoConfig(context.env); const requested = query.get("path"); if (requested) { const managed = validManagedPath(requested); const item = await file(config, managed); if (managed === "hugo.yaml") return json({ ok: true, item: { ...item, kind: "settings", title: "Site-instellingen", config: item.content } }); return json({ ok: true, item: { ...item, kind: "content", ...splitMarkdown(item.content) } }); } const items = await Promise.all((await listMarkdown(config)).map(async path => { const item = await file(config, path); const parsed = splitMarkdown(item.content); return { path, sha: item.sha, kind: "content", group: groupOf(path), title: titleOf(parsed.frontMatter, path.split("/").pop().replace(/\.md$/, "")), date: dateOf(parsed.frontMatter), draft: /^draft\s*:\s*true\s*$/mi.test(parsed.frontMatter) }; })); items.unshift({ path: "hugo.yaml", kind: "settings", group: "Instellingen", title: "Site-instellingen", date: "", draft: false }); return json({ ok: true, items }); } catch (error) { return handleError(error); } }
