backend:
  name: git-gateway
  branch: master  # or your default branch

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "snippets"
    label: "Snippets"
    folder: "content/snippets"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Titel", widget: "string" }
      - { name: "date", label: "Datum", widget: "datetime" }
      - { name: "draft", label: "Concept", widget: "boolean", default: true }
      - { name: "tags", label: "Tags", widget: "list", default: [] }
      - { name: "summary", label: "Samenvatting", widget: "text" }
      - label: "Omslag"
        name: "cover"
        widget: "object"
        required: false
        fields:
          - { name: "image", label: "Afbeelding", widget: "image", required: false }
          - { name: "alt", label: "Alt Text", widget: "string", required: false  }
      - { name: "body", label: "Inhoud", widget: "markdown" }
  - name: "homepage"
    label: "Homepage"
    files:
      - file: "content/homepage.md"
        label: "Homepage Content"
        name: "homepage"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Logo", name: "logo", widget: "image", required: false }
          - { label: "Introductie", name: "body", widget: "markdown" }
