backend:
  name: git-gateway
  branch: master  # or your default branch

media_folder: "static/uploads"
public_folder: "/uploads"

preview_styles: "static/preview.css"

collections:
  - name: "snippets"
    label: "Snippets"
    folder: "content/snippets"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "draft", label: "Draft", widget: "boolean", default: true }
      - { name: "tags", label: "Tags", widget: "list", default: [] }
      - { name: "summary", label: "Summary", widget: "text" }
      - label: "Cover"
        name: "cover"
        widget: "object"
        fields:
          - { name: "image", label: "Image", widget: "image" }
          - { name: "alt", label: "Alt Text", widget: "string" }
          - { name: "relative", widget: "hidden", default: true }
          - { name: "hiddenInList", label: "Hide in List View", widget: "boolean", default: false }
      - { name: "ShowToc", label: "Show Table of Contents", widget: "boolean", default: true }
      - { name: "body", label: "Body", widget: "markdown" }
