backend:
  name: git-gateway
  branch: master  # or your default branch

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "snippets"
    label: "Snippets"
    folder: "content/snippets"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Titel", widget: "string" }
      - { name: "date", label: "Datum", widget: "datetime" }
      - { name: "draft", label: "Concept", widget: "boolean", default: true }
      - { name: "tags", label: "Tags", widget: "list", default: [] }
      - { name: "summary", label: "Samenvatting", widget: "text" }
      - label: "Cover"
        name: "cover"
        widget: "object"
        required: false
        fields:
          - { name: "image", label: "Afbeelding", widget: "image" }
          - { name: "alt", label: "Alt Text", widget: "string" }
          - { name: "hiddenInList", label: "Verbergen in Lijstweergave", widget: "boolean", default: false }
      - { name: "ShowToc", label: "Toon Inhoudsopgave", widget: "boolean", default: true }
      - { name: "body", label: "Body", widget: "markdown" }
